server:
  port: 8080
logging:
  file: logInfo.log

spring:
  datasource:
     ### MySQL Connector/J 5.x   (旧版连接)
     ###  url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8
     ### MySQL Connector/J 6.x之后   (新版连接)
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


    ## 连接池相关的配置------------------------
    hikari:
    ## 最小空闲连接数量
      minimum-idle: 5
    ##连接池最大连接数
      maximum-pool-size: 10
     ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ##字母连接池
      pool-name: MyHikariCP
      ##连接池最大生命周期 值0标识无线生命周期，默认1800000即30分钟
      max-lifetime: 180000
      ##数据库连接超时时间，默认为30秒
      connection-timeout: 30000
      ###-----------------Redis相关配置-----------------------------------------
  redis:
      database: 0  # Redis数据库索引（默认为0）
      host: 127.0.0.1 # Redis服务器地址
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-idle: 8  # 连接池中的最大空闲连接 默认 8
          min-idle: 0  # 连接池中的最小空闲连接 默认 0
  jpa:
    properties:
     hibernate:
       hbm2ddl:
         auto: update
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  application:
    name: Spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest









